# Use root/example as user/password credentials
version: "2.2"

services:
  db:
    image: postgres:latest
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi-user
      - POSTGRES_PASSWORD=this-is-me-smashing-my-keyboard-or-something
      - POSTGRES_DB=fictional
    networks: 
      - web
    labels:
      - "traefik.enable=false"

  app:
    build: ./app
    command: uvicorn app.main:app --host 0.0.0.0 
    restart: unless-stopped
    networks: 
      - web
    volumes:
      - ./:/app
    environment:
      - "DB_HOST=postgresql://fastapi-user:this-is-me-smashing-my-keyboard-or-something@db:5432/fictional"
    depends_on:
      - db
    labels: 
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:sequeli.ctf.unswsecurity.com"
      - "traefik.port=8000"
      - "traefik.docker.network=web"

networks:
  web: 
    external: true